### ISSUE TITLE
3d landmarks

### ISSUE THREAD

**Issue by georgeYanch** [rolpotamias/WiLoR#1]
Hi, first of all, thank you for your amazing work, the results are truly impressive!

I have several questions:

1) I'd like to get predicted 3d landmarks, how do I transform raw output to image coordinates?
2) The config says that model will predict 15 joints, but 'pred_keypoints_3d' has shape of (21, 3), are they not the same?
3) Is there any possibility to use rotation matrices predicted for each joint to estimate yaw rotation angle of the palm/wrist?

**Comment by rolpotamias** [comment]
Hi 
1. We provide the 3D landmarks in the model's output (output['pred_keypoints_3d']). We also provide the projected 2D landmarks in the image coordinates (output['pred_keypoints_2d']). You can refer to this part of the [code](https://github.com/rolpotamias/WiLoR/blob/main/wilor/models/wilor.py#L155) . 
2. There are indeed 15 Joints with 5 additional finger tips and the wrist. Please refer to [MANO](https://mano.is.tue.mpg.de/) for the corresponding landmark annotations. 
3. Yes, we provide the global rotation as part of the [output](https://github.com/rolpotamias/WiLoR/blob/main/wilor/models/wilor.py#L143).
