### ISSUE TITLE
Given camera (K, R, t), how to modified them to the code?

### ISSUE THREAD

**Issue by 1524101973** [rolpotamias/WiLoR#10]
Thank you for sharing the wonderful work!
May I ask you how can I modified the code if I have already got an extrinsic matrix of the camera?
Thank you

**Comment by Boey-li** [comment]
Hello, I have the same issue, have you solved this problem?

**Comment by rolpotamias** [comment]
I think this can not be easily solved. 

You can set you camera intrinsics and extrinsic [here](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L81) but if there is a big discrepancy between the focal lengths it will result in bad image-alignment.

**Comment by GuoPingPan** [comment]
@rolpotamias  May I ask why a focal length as large as 5000 was used for the training?

**Comment by PannagaS** [comment]
Even I am facing the same issue. I have collected the data, and have updated the config file to the correct focal length of my camera, but the camera translation is way off! When the ground truth is approximately 30cm from the camera, the z-displacement predicted by the model (cam_t) is 1.1m which is very wrong. I don't know apart from focal length, is there anything else I need to change to run WiLoR on my own dataset?

@rolpotamias @1524101973 @GuoPingPan  @Boey-li
