### ISSUE TITLE
Good job！I have simplified WiLoR into a Python package

### ISSUE THREAD

**Issue by warmshao** [rolpotamias/WiLoR#13]
https://github.com/warmshao/WiLoR-mini

Now you can use pip install git+https://github.com/warmshao/WiLoR-mini to use WiLoR!

https://github.com/user-attachments/assets/ace28e01-732e-487e-ac6b-1359fa7388e2

**Comment by rolpotamias** [comment]
Thank you very much. This looks amazing. I will update the readme file to include this :)
