### ISSUE TITLE
How to Construct a Custom Dataset?

### ISSUE THREAD

**Issue by Unimendacity** [rolpotamias/WiLoR#16]
This work is truly impressive.
Could you please provide guidance on how to build a custom dataset?

**Comment by rolpotamias** [comment]
Could you please give me some additional details on the dataset that you would like to build? 

We will release WHIM dataset over the next weeks.

**Comment by Unimendacity** [comment]
I have a set of images with gloves and would like to detect their 3D poses.

Could you provide a detailed guide on how to process these images and build a dataset that can be used to train WiLoR effectively?

Thank you!

**Comment by rolpotamias** [comment]
Have you tried reconstructing any of those images with WiLoR directly? 

I do not think that extracting the poses with WiLoR and training on top of the predicted poses will offer anything to the performance. 

If Wilor does not work well on hands with gloves I would suggest following an optimization method like the one described in `[Sec. 3 ](https://arxiv.org/pdf/2409.12259)`

**Comment by PannagaS** [comment]
@rolpotamias how do I make sure to change config parameters to match my own dataset? Like I have RGB images of my hand and I am currently running an inference using demo.py. But I would like to know where and how and what all camera parameters I need to change to make sure the 3D rotation (global orientation) and 3D translation of camera I'm getting is actually according to the camera I am using?? Please let me know, any help is very deeply appreciated.
