### ISSUE TITLE
Regarding the hand pose parameter for model output

### ISSUE THREAD

**Issue by xiyangyang99** [rolpotamias/WiLoR#18]
The result of the hand pose parameter output is as follows: Which tensor data is left hand and which is right hand?
hand_pose tensor([[[[ 0.8847, -0.4488, -0.1259],
          [ 0.3960,  0.8662, -0.3049],
          [ 0.2459,  0.2199,  0.9440]],

         [[ 0.9770,  0.1305,  0.1684],
          [-0.1653,  0.9630,  0.2130],
          [-0.1343, -0.2360,  0.9624]],

         [[ 0.9564, -0.2319,  0.1777],
          [ 0.2891,  0.6632, -0.6903],
          [ 0.0423,  0.7116,  0.7013]],

         [[ 0.9478, -0.2770, -0.1580],
          [ 0.2315,  0.9384, -0.2565],
          [ 0.2193,  0.2066,  0.9535]],

         [[ 0.9920, -0.0765, -0.1000],
          [ 0.1077,  0.9267,  0.3601],
          [ 0.0651, -0.3680,  0.9275]],

         [[ 0.9775, -0.1271,  0.1683],
          [ 0.1477,  0.9822, -0.1160],
          [-0.1506,  0.1382,  0.9789]],

         [[ 0.7888, -0.3169,  0.5267],
          [ 0.3498,  0.9360,  0.0392],
          [-0.5054,  0.1533,  0.8491]],

         [[ 0.9523,  0.0939, -0.2903],
          [-0.0197,  0.9684,  0.2487],
          [ 0.3044, -0.2312,  0.9241]],

         [[ 0.9432, -0.2498,  0.2189],
          [ 0.2578,  0.9662, -0.0085],
          [-0.2094,  0.0645,  0.9757]],

         [[ 0.9822, -0.1846,  0.0336],
          [ 0.1874,  0.9554, -0.2285],
          [ 0.0101,  0.2307,  0.9730]],

         [[ 0.9817,  0.1176, -0.1499],
          [-0.0592,  0.9361,  0.3466],
          [ 0.1811, -0.3314,  0.9260]],

         [[ 0.9504, -0.1605,  0.2666],
          [ 0.1324,  0.9839,  0.1204],
          [-0.2816, -0.0792,  0.9563]],

         [[ 0.9590, -0.0964, -0.2664],
          [-0.1735,  0.5433, -0.8214],
          [ 0.2239,  0.8340,  0.5043]],

         [[ 0.9215, -0.3585, -0.1495],
          [ 0.3752,  0.7219,  0.5815],
          [-0.1005, -0.5919,  0.7997]],

         [[ 0.9918,  0.0822, -0.0980],
          [-0.0983,  0.9800, -0.1728],
          [ 0.0818,  0.1810,  0.9801]]],

        [[[ 0.8322, -0.4228, -0.3586],
          [ 0.3143,  0.8926, -0.3231],
          [ 0.4568,  0.1562,  0.8758]],

         [[ 0.9769,  0.1741,  0.1235],
          [-0.1944,  0.9647,  0.1776],
          [-0.0882, -0.1975,  0.9763]],

         [[ 0.9759, -0.1814,  0.1216],
          [ 0.2145,  0.6916, -0.6897],
          [ 0.0411,  0.6991,  0.7139]],

         [[ 0.4906, -0.8321, -0.2586],
          [ 0.8587,  0.5121, -0.0189],
          [ 0.1482, -0.2128,  0.9658]],

         [[ 0.8498, -0.3975, -0.3462],
          [ 0.4882,  0.8413,  0.2323],
          [ 0.1989, -0.3664,  0.9089]],

         [[ 0.9611, -0.2408,  0.1354],
          [ 0.2507,  0.9662, -0.0606],
          [-0.1162,  0.0922,  0.9889]],

         [[ 0.3160, -0.9133,  0.2571],
          [ 0.5154,  0.3927,  0.7617],
          [-0.7966, -0.1082,  0.5948]],

         [[ 0.7836, -0.3697, -0.4994],
          [ 0.5036,  0.8486,  0.1620],
          [ 0.3639, -0.3784,  0.8511]],

         [[ 0.8538, -0.5206,  0.0085],
          [ 0.5197,  0.8532,  0.0447],
          [-0.0305, -0.0337,  0.9990]],

         [[ 0.2936, -0.9432,  0.1554],
          [ 0.9264,  0.3208,  0.1969],
          [-0.2356,  0.0861,  0.9680]],

         [[ 0.8454, -0.3435, -0.4091],
          [ 0.5136,  0.7333,  0.4456],
          [ 0.1469, -0.5868,  0.7963]],

         [[ 0.9544, -0.2367,  0.1820],
          [ 0.2066,  0.9636,  0.1699],
          [-0.2156, -0.1245,  0.9685]],

         [[ 0.9585, -0.0270, -0.2838],
          [-0.2206,  0.5604, -0.7983],
          [ 0.1806,  0.8278,  0.5312]],

         [[ 0.9144, -0.3550, -0.1947],
          [ 0.3906,  0.6465,  0.6554],
          [-0.1068, -0.6753,  0.7298]],

         [[ 0.9536,  0.2979, -0.0426],
          [-0.2999,  0.9292, -0.2160],
          [-0.0248,  0.2187,  0.9755]]]], device='cuda:0')

**Comment by rolpotamias** [comment]
You can determine which hand (right or left) corresponds to each pose from [this list](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L101).

**Comment by xiyangyang99** [comment]
> You can determine which hand (right or left) corresponds to each pose from [this list](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L101).

The output hand pose data is in the hand pose [2,15,3] dimension. How can I convert this format to SMPL format with dimensions of [2,15,3]? Thank you very much, author

**Comment by xiyangyang99** [comment]
> You can determine which hand (right or left) corresponds to each pose from [this list](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L101).

The output hand pose data is in the hand pose [2,15,3,3] dimension. How can I convert this format to SMPL format with dimensions of [2,15,3]? Thank you very much, author
