### ISSUE TITLE
Replication for Freihand results

### ISSUE THREAD

**Issue by taeyunwoo** [rolpotamias/WiLoR#22]
Dear authors,

First of all, thank you for your work!

How can I replicate your results on FreiHand dataset?
Can I get the checkpoint for Freihand training WiLoR model?

Sincerely,
TY

**Comment by rolpotamias** [comment]
Hi there, 

Sorry for my late reply it was quite busy lately. 
You can find my evaluation script [here](https://gist.github.com/rolpotamias/17cf7c5cba0bd5f3d970758217d37c6c).
You will need to modify the  [L16](https://gist.github.com/rolpotamias/17cf7c5cba0bd5f3d970758217d37c6c#file-eval_wilor_freihand-py-L16) the path of the FreiHand dataset. 

It uses the [original codebase](https://github.com/lmb-freiburg/freihand/blob/master/pred.py) with a modified prediction function part to use WiLoR. 

You can then use the extracted json file to upload to the [Codalab](https://competitions.codalab.org/competitions/21238) or use the [eval.py](https://github.com/lmb-freiburg/freihand/blob/master/eval.py) provided by the Freihand authors.
