### ISSUE TITLE
cuda version error

### ISSUE THREAD

**Issue by ccchen091** [rolpotamias/WiLoR#6]
Hello, I would like to ask if my cuda version is version 11.7, and then I always get an error after installing all the installation packages as you said, RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.

**Comment by rolpotamias** [comment]
Hi there, 
Glad you solved your issue. 

You can get the 3D keypoints from [here](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L93) and you can also get the 2D keypoint projections from the output dictionary as `out['pred_keypoints_2d']`

**Comment by ccchen091** [comment]
Thank you for your response!
I would like to ask what coordinate system this 3D coordinate is? Is it an image coordinate system or a world coordinate system or what? Because I noticed that the values of this 3D coordinate are all between -1 and 1

**Comment by rolpotamias** [comment]
The 3D coordinates are in a translated MANO canonical system (translated by cam_t) .

**Comment by ccchen091** [comment]
Thank you for your patient explanation!!! 
So can I understand it like this: I first save the 3D key coordinates in the mano coordinate system, and then calibrate the internal and external parameters of my camera, and through the internal and external parameters, I can convert the 3D key point coordinates in the mano coordinate system to the world coordinate system or image coordinate system.

**Comment by rolpotamias** [comment]
Yes. I have updated the `demo.py` to include such projection in the image coordinate system (please check [here](https://github.com/rolpotamias/WiLoR/blob/main/demo.py#L97) ).
