### ISSUE TITLE
speed up inference on single-image stream

### ISSUE THREAD

**Issue by MandiZhao** [rolpotamias/WiLoR#9]
nice work! I have a webcam streaming images one at a time, and I found the model forwarding still shows a big delay (processing 1 or 2 frames per sec), wondering if you have tips to speed this up?

**Comment by rolpotamias** [comment]
The inference time highly depends on the GPU. I have tested on both NVIDIA RTX 4090 and A100 and managed to achieve around 15-20 FPS depending on the number of hands in the image. 
I guess this can be further improved if you remove some non-necessary variables and transitions between CPU and GPU.

**Comment by MandiZhao** [comment]
@rolpotamias thanks for responding! But I'm also using a 4090. 
Do you batch the images when you compute FPS? I wonder if it's because I'm running one image at a time. I batch it following this code: https://github.com/rolpotamias/WiLoR/blob/93142c7683b90d06c9f0484689076b29e390cf52/gradio_demo.py#L61, or is there a faster way to do it?

**Comment by ruoyiqiao** [comment]
Hi, @MandiZhao. I think there are a few points that might be helpful:

1. turn off any rendering processes. This can provide a significant performance boost.
2. Process detected hands in a single frame in one batch.
3. GPU might not be the bottleneck, profile may be helpful to identify this.

I tried the demo code on 3090 which gives ~10Hz inference rate. Hope helpful!

**Comment by rolpotamias** [comment]
Hi @MandiZhao sorry for the late reply. 

May I ask if you have measured the model inference pass? It should on average take around 25ms for a single hand. 

Maybe, as @ruoyiqiao  suggested, the rendering cause the bottleneck in your inference.

**Comment by xiyangyang99** [comment]
> Hi, @MandiZhao. I think there are a few points that might be helpful:
> 
> 1. turn off rendering part. This can provide a significant performance boost.
> 2. Process detected hands in a single frame in one batch.
> 3. GPU might not be the bottleneck, profile may be helpful to identify this.
> 
> I tried the demo code on 3090 which gives ~11Hz inference rate.

how to  turn off rendering part ?
